!!+ RandomNormal.f90
!!
!!     This program produces N normally distributed random numbers, which are generated by the polar method.
!!     The normally distributed random numbers are stored in the file random_normal_DATA.dat in the data folder.
!!     With the file histogram.plt a histogram can be created from the random numbers.
!!
!!     compile with: > make RandomNormal
!!
!!     usage:        > ./RandomNormal N
!!
!!     expected result:
!!                     >> .dat file that contains N normally distributed numbers
!!
PROGRAM RandomNormal
    USE RandomNumbers_mod
    IMPLICIT NONE
    integer :: i, n, GetN
    ! set n given by cmd-line argument
    n = GetN()
    
    !Prepares the .dat file where the normally distributed numbers will be stored
    OPEN(UNIT=23, FILE='data/random_normal_DATA.dat')
    
    !loop to store N normally distributed numbers in a .dat file
    DO i=1,n
        WRITE(23,*) random_normal()
    END DO
  END PROGRAM RandomNormal


  FUNCTION GetN() RESULT (n)
    IMPLICIT NONE
    
    INTEGER              :: n
    CHARACTER(LEN=32)    :: arg
  
    ! get n from command-line arguments
    IF (iargc()==1) THEN
       CALL getarg(1,arg)
       READ(arg, *, ERR=99) n        ! read n from string arg 
       RETURN                        ! on success exit here
    ELSE
       ! no or too many cmd-line arguments, aborting
       PRINT*, 'RandomNumbers requires exactly one argument.'
       PRINT*, '$ ./RandomNumbers <n>'
       STOP
    END IF
  
  99 PRINT*, 'Argument must be INTEGER value!' 
    PRINT*, '$ ./RandomNumbers <n>'
    STOP
  
  END FUNCTION GetN
